import StoreHydration from "@/contexts/store-hydration";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";
import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Turborepo Starter - Client: (NextJS/Zustand/Tanstack-Query)",
  description: "Generated by Jaekyeong Yuk",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <TanstackQueryProvider>
        <body className={inter.className}>
          <StoreHydration />
          {children}
        </body>
      </TanstackQueryProvider>
    </html>
  );
}
