import RecoilProvider from "@/providers/RecoilProvider";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";
import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Turborepo Starter - Client: (NextJS/Recoil/Tanstack-Query)",
  description: "Generated by Jaekyeong Yuk",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <TanstackQueryProvider>
        <RecoilProvider>
          <body className={inter.className}>{children}</body>
        </RecoilProvider>
      </TanstackQueryProvider>
    </html>
  );
}
